services:
  node:
    build: node
    ports:
      - 3000:3000

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  redis:

endpoints:
  redis:
    - path: /
      service: redis
      port: 6379
  web:
    - path: /
      service: node
      port: 3000